version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins-server
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins-network
    volumes:
      - jenkins-data:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    privileged: true  # Para poder usar Docker dentro del contenedor
    dns:
      - 8.8.8.8
    restart: unless-stopped

networks:
  jenkins-network:
    driver: bridge

volumes:
  jenkins-data:
    driver: local
