name: Build and Publish Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build JAR with Maven
      working-directory: java/app
      run: mvn clean package --no-transfer-progress

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/app:latest -f java/app/Dockerfile .

    - name: Push Docker image to GHCR
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/app:latest
