name: Build and Run Maven Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'  # Usa 'temurin' en lugar de 'adoptopenjdk'

      - name: Verificar estructura de directorios
        run: ls -R java  # Verifica que el directorio 'java' existe y tiene subdirectorios

      - name: Ejecutar Maven Build
        working-directory: java/app  # Cambiar al directorio donde está tu pom.xml
        run: mvn clean install

      - name: Ejecutar pruebas
        working-directory: java/app  # Cambiar al mismo directorio para ejecutar las pruebas
        run: mvn test
